module.exports = {
  QUESTION_TYPES: {
    MULTI_ONE: 'multi_one',
    MULTI_MULTI: 'multi_multi',
    FREETEXT: 'freetext'
  },
  RESPONSE_STATUSES: {
    IN_PROGRESS: 'IN PROGRESS',
    COMPLETE: 'COMPLETE',
    SCORING_COMPLETE: 'SCORING COMPLETE'
  },
  SCORING_STATUSES: {
    IN_PROGRESS: 'IN PROGRESS',
    COMPLETE: 'COMPLETE'
  }
};